version: "3.8"
services:
  chess:
    image: shashwatmath/chess:0.2
    #build: .
    networks:
      dc1ring:
        ipv4_address: 127.0.0.6
    depends_on:
      - cas-node1
    ports:
      - "5000:5000"
  cas-node1:
    image: cassandra
    container_name: cas-node1
    networks:
      dc1ring:
        ipv4_address: 127.0.0.2
    volumes:
      - /data/cas-node1:/var/lib/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=cas-node1,cas-node3
      - START_RPC=false
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.2
      - CASSANDRA_RPC_ADDRESS=127.0.0.2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - 9042:9042
  cas-node2:
    image: cassandra
    container_name: cas-node2
    networks:
      dc1ring:
        ipv4_address: 127.0.0.3
    volumes:
      - /data/cas-node2:/var/lib/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=cas-node1,cas-node3
      - START_RPC=false
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.3
      - CASSANDRA_RPC_ADDRESS=127.0.0.3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - 9043:9042
    depends_on:
      - cas-node1
  cas-node3:
    image: cassandra
    container_name: cas-node3
    networks:
      dc1ring:
        ipv4_address: 127.0.0.4
    volumes:
      - /data/cas-node3:/var/lib/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=cas-node1,cas-node2
      - START_RPC=false
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.4
      - CASSANDRA_RPC_ADDRESS=127.0.0.4
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - 9044:9042
    depends_on:
      - cas-node1
  cas-node4:
    image: cassandra
    container_name: cas-node4
    networks:
      dc1ring:
        ipv4_address: 127.0.0.5
    volumes:
      - /data/cas-node4:/var/lib/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=cas-node1,cas-node3
      - START_RPC=false
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.5
      - CASSANDRA_RPC_ADDRESS=127.0.0.5
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9142
    ports:
      - 9045:9042
    depends_on:
      - cas-node1

networks:
  dc1ring:
    ipam:
      driver: default
      config:
        - subnet: 127.0.0.0/16