version: "3.8"
services:
  cas-chess:
    image: shashwatmath/chess:0.3
    #build: .
    networks:
      dc1ring:
        ipv4_address: 172.18.0.6
    depends_on:
      - cas-node4
    ports:
      - 5000:5000
  cas-node1:
    image: cassandra
    container_name: cas-node1
    networks:
      dc1ring:
        ipv4_address: 172.18.0.2
    volumes:
      - /data/cas-node1:/opt/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=172.18.0.2
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - LISTEN_ADDRESS=172.18.0.2
      - RPC_ADDRESS=172.18.0.2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    command: cassandra -f -a
  cas-node2:
    image: cassandra
    container_name: cas-node2
    networks:
      dc1ring:
        ipv4_address: 172.18.0.3
    volumes:
      - /data/cas-node2:/opt/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=172.18.0.2
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack2
      - LISTEN_ADDRESS=172.18.0.3
      - RPC_ADDRESS=172.18.0.3
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    depends_on:
      - cas-node1
    command: cassandra -f -a
  cas-node3:
    image: cassandra
    container_name: cas-node3
    networks:
      dc1ring:
        ipv4_address: 172.18.0.4
    volumes:
      - /data/cas-node3:/opt/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=172.18.0.3,172.18.0.2
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack1
      - LISTEN_ADDRESS=172.18.0.4
      - RPC_ADDRESS=172.18.0.4
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    depends_on:
      - cas-node2
    command: cassandra -f -a
  cas-node4:
    image: cassandra
    container_name: cas-node4
    networks:
      dc1ring:
        ipv4_address: 172.18.0.5
    volumes:
      - /data/cas-node4:/opt/cassandra/data
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_SEEDS=172.18.0.3,172.18.0.2
      - CASSANDRA_CLUSTER_NAME=cl-chess
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
      - LISTEN_ADDRESS=172.18.0.5
      - RPC_ADDRESS=172.18.0.5
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    depends_on:
      - cas-node2
    command: cassandra -f -a

networks:
  dc1ring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16